steps:
- name: 'ubuntu'
  entrypoint: bash
  args:
  - -c
  - |
    # Clean up the workspace
    rm -rf *

    # Clone the repository
    git clone --depth 1 `https://github.com/mamounalghaslan/rag-proto .
    cd .
    git checkout main

    # Install dependencies (Adapt to your needs.  Example for npm)
    npm install

    # Build your application (Adapt to your needs. Example for npm)
    npm run build

    # Build the Docker image (using your existing image name)
    docker build -t me-central2-docker.pkg.dev/gen-ai-436712/cloud-run-source-deploy .

    # Push the Docker image
    gcloud docker --project=gen-ai-436712 push me-central2-docker.pkg.dev/gen-ai-436712/cloud-run-source-deploy

images:
- 'me-central2-docker.pkg.dev/gen-ai-436712/cloud-run-source-deploy'
