steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/rag-proto', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['push', 'gcr.io/$PROJECT_ID/rag-proto']
images:
- 'gcr.io/$PROJECT_ID/rag-proto'
