steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/rag-proto', '.'] #Build and tag
- name: 'gcr.io/cloud-builders/gcloud' #Push to GCR
  args: ['docker', '--', 'push', 'gcr.io/$PROJECT_ID/rag-proto']
images:
- 'gcr.io/$PROJECT_ID/rag-proto'